name: Tests

on:
  push:
    branches:
      - main
      - master
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    strategy:
      matrix:
        yarn-version: [14, 15, 16]

    steps:
      - uses: actions/checkout@v3
      - name: Vendors Setup
        run: |
          mkdir vendors
          git clone https://github.com/Harry-Hopkinson/OpenGL-Files.git
      - name: Compile
        run: |
          make test
